sentry:
  dsn: "%env(SENTRY_DSN)%"
  options:
    environment: '%env(APP_ENV)%'
    attach_stacktrace: true
    sample_rate: 1.0
    traces_sample_rate: 1.0

monolog:
  handlers:
    sentry:
      type: service
      id: Sentry\Monolog\Handler

services:
  Sentry\Monolog\Handler:
    arguments:
      $hub: '@Sentry\State\HubInterface'
      $level: !php/const Monolog\Logger::INFO
