version: "3.8"
services:

  database:
    image: 'mysql:8.0'
    platform: linux/x86_64
    container_name: symfony-sandbox-db
    working_dir: /application
    volumes:
      - .:/application
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=symfony-sandbox
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    ports:
      - "3310:3306"

  webserver:
    image: nginx:alpine
    container_name: symfony-sandbox-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8085:80"

  php-fpm:
    build: docker/php-fpm
    container_name: symfony-sandbox-php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
