# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    doctrine.orm.entity_manager.class: Doctrine\ORM\EntityManager
services:
    # default configuration for services in *this* file
    _defaults:
        public: true
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\UserRepository:
        tags: ['doctrine.repository_service']

    Doctrine\ORM\EntityManager:
        alias: doctrine.orm.entity_manager


    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        class: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher

    App\Exception\LogicException:
        arguments:
            $message: 'Your exception message here'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
